//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiQExcelRobot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Konton : global::System.Configuration.ApplicationSettingsBase {
        
        private static Konton defaultInstance = ((Konton)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Konton())));
        
        public static Konton Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Maximized {
            get {
                return ((bool)(this["Maximized"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Kärnkonto I Privat</string>
  <string>Kärnkonto II Privat</string>
  <string>Kärnkonto Student</string>
  <string>Servicekonto</string>
  <string>E-sparkonto</string>
  <string>Österlenkonto</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KontoMyndig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KontoMyndig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Kompiskonto</string>
  <string>E-sparkonto</string>
  <string>Österlenkonto</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KontoOmyndig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KontoOmyndig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Internetbank Privat (BankID)</string>
  <string>Internetbank Privat (SydID)</string>
  <string>Internetbank Bas (BankID)</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IntBankMyndig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IntBankMyndig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Internetbank Ung (BankID)</string>
  <string>Internetbank Ung (SydID)</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IntBankOmyndig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IntBankOmyndig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Kundnummer</string>
  <string>Konto1</string>
  <string>Konto2</string>
  <string>Konto3</string>
  <string>Internetbank</string>
  <string>Telefonbank</string>
  <string>VISA</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Labels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Labels"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gemensam disprätt förmyndare")]
        public string ChkGemDisp {
            get {
                return ((string)(this["ChkGemDisp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Omyndig disprätt")]
        public string ChkOmyndigDisp {
            get {
                return ((string)(this["ChkOmyndigDisp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kärnkontopaket")]
        public string ChkCoreAccount {
            get {
                return ((string)(this["ChkCoreAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kopplat konto")]
        public string LblConnectedAccount {
            get {
                return ((string)(this["LblConnectedAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Förmyndare 1")]
        public string LblCustodian1 {
            get {
                return ((string)(this["LblCustodian1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Förmyndare 2")]
        public string LblCustodian2 {
            get {
                return ((string)(this["LblCustodian2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medkontohavare")]
        public string lblAccountCoowner {
            get {
                return ((string)(this["lblAccountCoowner"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
        public string ExcelFilePath {
            get {
                return ((string)(this["ExcelFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Robot.exe")]
        public string RobotFilePath {
            get {
                return ((string)(this["RobotFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2;Kundnummer")]
        public string ecPersNbr {
            get {
                return ((string)(this["ecPersNbr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3;Kundnummer Förmyndare 1")]
        public string ecPersNbrCareT1 {
            get {
                return ((string)(this["ecPersNbrCareT1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4;Kundnummer Förmyndare 1")]
        public string ecPersNbrCareT2 {
            get {
                return ((string)(this["ecPersNbrCareT2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5;Konto 1")]
        public string ecKonto1 {
            get {
                return ((string)(this["ecKonto1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6;Konto 1 Medkontohavare")]
        public string ecKonto1Coown {
            get {
                return ((string)(this["ecKonto1Coown"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8;Konto 1 Gemensam Disp")]
        public string ecKonto1ComDisp {
            get {
                return ((string)(this["ecKonto1ComDisp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9;Konto 1 Omyndig Disprätt")]
        public string ecKonto1Minor {
            get {
                return ((string)(this["ecKonto1Minor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10;Konto 2")]
        public string ecKonto2 {
            get {
                return ((string)(this["ecKonto2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11;Konto 2 Medkontohavare")]
        public string ecKonto2Coown {
            get {
                return ((string)(this["ecKonto2Coown"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13;Konto 2 Gemensam Disp")]
        public string ecKonto2ComDisp {
            get {
                return ((string)(this["ecKonto2ComDisp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14;Konto 2 Omyndig Disprätt")]
        public string ecKonto2Minor {
            get {
                return ((string)(this["ecKonto2Minor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15;Konto 3")]
        public string ecKonto3 {
            get {
                return ((string)(this["ecKonto3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16;Konto 3 Medkontohavare")]
        public string ecKonto3Coown {
            get {
                return ((string)(this["ecKonto3Coown"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18;Konto 3 Gemensam Disp")]
        public string ecKonto3ComDisp {
            get {
                return ((string)(this["ecKonto3ComDisp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19;Konto 3 Omyndig Disprätt")]
        public string ecKonto3Minor {
            get {
                return ((string)(this["ecKonto3Minor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20;Internetbank")]
        public string ecInternetbank {
            get {
                return ((string)(this["ecInternetbank"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22;Internetbank Kärnkonto")]
        public string ecInternetbankCore {
            get {
                return ((string)(this["ecInternetbankCore"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23;Internetbank Kopplad Konto")]
        public string ecInternetbankConn {
            get {
                return ((string)(this["ecInternetbankConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24;Telefonbank")]
        public string ecPhonebank {
            get {
                return ((string)(this["ecPhonebank"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25;Telefonbank Kopplad Konto")]
        public string ecPhonebankConn {
            get {
                return ((string)(this["ecPhonebankConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26;VISA")]
        public string ecVisa {
            get {
                return ((string)(this["ecVisa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27;VISA Kopplad Konto")]
        public string ecVisaConn {
            get {
                return ((string)(this["ecVisaConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Myndig")]
        public string lblMyndig {
            get {
                return ((string)(this["lblMyndig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Omyndig")]
        public string lblOmyndig {
            get {
                return ((string)(this["lblOmyndig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1;Kontotyp")]
        public string ecAccountType {
            get {
                return ((string)(this["ecAccountType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExcel {
            get {
                return ((bool)(this["ShowExcel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartRobot {
            get {
                return ((bool)(this["StartRobot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28;Fiktiv")]
        public string ecFiktiv {
            get {
                return ((string)(this["ecFiktiv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Upprätta Telefonbank")]
        public string ChkOrderTfnBank {
            get {
                return ((string)(this["ChkOrderTfnBank"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beställ VISA")]
        public string ChkOrderVisa {
            get {
                return ((string)(this["ChkOrderVisa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beställ VISA medkontohavare")]
        public string ChkExtraVisaKort {
            get {
                return ((string)(this["ChkExtraVisaKort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29;Extra VISA")]
        public string ecExtraVisa {
            get {
                return ((string)(this["ecExtraVisa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Internetbank Privat (SydID)</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IntBankMyndigFikt {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IntBankMyndigFikt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Internetbank Ung (SydID)</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IntBankOmyndigFikt {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IntBankOmyndigFikt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Upprätta Telefonbank Ung")]
        public string ChkOrderTfnBankUng {
            get {
                return ((string)(this["ChkOrderTfnBankUng"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beställ VISA Online")]
        public string ChkOrderVisaOnline {
            get {
                return ((string)(this["ChkOrderVisaOnline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Den editerade informationen kommer att sparas i Excel, därefter kommer automatiskt skapande av valda produkter att påbörjas.

OBS! Under denna process kommer datorns mus och tangentbord att vara låsta!

Spara och stäng öppna dokument, kontrollera att Kerne är startad och tryck därefter på OK eller avbryt.")]
        public string saveMsg {
            get {
                return ((string)(this["saveMsg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Du har data som inte har sparats. Vill du fortsätta stänga?")]
        public string unsavedData {
            get {
                return ((string)(this["unsavedData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Du har data som inte har sparats. Vill du fortsätta med ny sida?")]
        public string unsavedDataNewPage {
            get {
                return ((string)(this["unsavedDataNewPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Du måste välja ett konto ovanför innan du kan välja ett medkontohavare.")]
        public string mustChooseAccount {
            get {
                return ((string)(this["mustChooseAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Felaktig personnummer")]
        public string wrongPersnbr {
            get {
                return ((string)(this["wrongPersnbr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21;Användarnummer")]
        public string ecUserNumberCtrl {
            get {
                return ((string)(this["ecUserNumberCtrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7;Konto 1 Disprätt")]
        public string ecDispRattCtrl1 {
            get {
                return ((string)(this["ecDispRattCtrl1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12;Konto 2 Disprätt")]
        public string ecDispRattCtrl2 {
            get {
                return ((string)(this["ecDispRattCtrl2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17;Konto 3 Disprätt")]
        public string ecDispRattCtrl3 {
            get {
                return ((string)(this["ecDispRattCtrl3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Användarnummer")]
        public string LblUserNumberCtrl {
            get {
                return ((string)(this["LblUserNumberCtrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dispositionsrätt")]
        public string LblDispRattCtrl {
            get {
                return ((string)(this["LblDispRattCtrl"]));
            }
        }
    }
}
